//@version=5
//https://github.com/mr-s8

strategy("ema+bb%b+adx+ao", overlay=true, initial_capital=1000, default_qty_value=10, default_qty_type= strategy.percent_of_equity)

//inputs
takeprofit=input.float(defval = 1.0 , title = "Take-Profit", minval = 0.1 , maxval = 4 , step = 0.1 )/100
stoploss=input.float(defval = 2.0 , title = "Stop-Loss", minval = 0.1 , maxval = 4 , step = 0.1 )/100


ema5_len=input(5,title="EMA fastest")
ema21_len=input(21,title="EMA fast")
ema50_len=input(50,title="EMA slow")
ema200_len=input(200,title="EMA slowest")         

bboversold=input(0.25, title="BB Oversold")
bboverbrought = input(0.75, title="BB Overbrought")

aooversold=input(-2.00,title="A0 Below for Shorts")
aooverbrought=input(2.00,title="AO Above for longs")

adxvalue=input(15,title="ADX LEVEL TO STAY ABOVE")
//not that important:
adxlen = input(14, title="(ADX Smoothing)")
dilen = input(14, title="(DI Length)")




//Indicator code
//4 Ema's
ema5=ta.ema(close,ema5_len)
ema21=ta.ema(close,ema21_len)
ema50=ta.ema(close,ema50_len)
ema200=ta.ema(close,ema200_len)
// BB (code from tradingview)
basis=ta.sma(close,20)
dev = 2 * ta.stdev(close,20)
upper=basis+dev
Lower=basis-dev
bbr=(close - Lower)/(upper - Lower)
// AO (code from tradingview)
ao = ta.sma(hl2,5) - ta.sma(hl2,34)
// ADX (code from tradingview)
dirmov(len) =>
	up = ta.change(high)
	down = -ta.change(low)
	plusDM = na(up) ? na : (up > down and up > 0 ? up : 0)
	minusDM = na(down) ? na : (down > up and down > 0 ? down : 0)
	truerange = ta.rma(ta.tr, len)
	plus = fixnan(100 * ta.rma(plusDM, len) / truerange)
	minus = fixnan(100 * ta.rma(minusDM, len) / truerange)
	[plus, minus]
adx(dilen, adxlen) =>
	[plus, minus] = dirmov(dilen)
	sum = plus + minus
	adx = 100 * ta.rma(math.abs(plus - minus) / (sum == 0 ? 1 : sum), adxlen)
sig = adx(dilen, adxlen)
// End of ADX and DI Code
//End of Indicators

//Plotting
plot(ema5,title="EMA5",color=color.blue)
plot(ema21,title="EMA21",color=color.purple)
plot(ema50,title="EMA50",color=color.yellow)
plot(ema200,title="EMA200",color=color.white)

plot(ao, title="ao value")

plot(sig, color=color.red, title="ADX")

plot(bbr,title="BB Value", color=color.green, linewidth=2, style=plot.style_line)
//logic
aolong=ao > aooverbrought
aoshort=ao < aooversold

bblong = bbr > bboverbrought
bbshort = bbr < bboversold

ema_long = ema5>ema21 and ema50>ema200 
ema_short = ema5<ema21 and ema50<ema200 

adxlongshort=sig >adxvalue

notintrade=strategy.position_size<=0


//execution

if ema_long and bblong and aolong and adxlongshort and notintrade
    strategy.entry("long", strategy.long)
strategy.exit(id="tpsllong", from_entry="long", limit = strategy.position_avg_price*(1+takeprofit), stop =strategy.position_avg_price*(1-stoploss))

if ema_short and bbshort and aoshort and adxlongshort and notintrade
    strategy.entry("short", strategy.short)
strategy.exit("exit", "short", limit = strategy.position_avg_price*(1-takeprofit), stop =strategy.position_avg_price*(1+stoploss))
